### ISSUE TITLE
Error: Cannot find module 'string'

### ISSUE THREAD

**Issue by ToeiRei** [NodeBB-Community/nodebb-plugin-telegram-notifications#14]
2018-03-04T19:59:58.078Z [19337] - [31merror[39m: Error: Cannot find module 'string'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at Object.<anonymous> (/home/board/nodebb/node_modules/nodebb-plugin-telegram-notifications/library.js:13:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.Plugins.requireLibrary (/home/board/nodebb/src/plugins.js:44:32)
    at registerHooks (/home/board/nodebb/src/plugins/load.js:180:13)
    at /home/board/nodebb/src/plugins/load.js:138:6
    at /home/board/nodebb/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (/home/board/nodebb/node_modules/async/dist/async.js:1055:9)
2018-03-04T19:59:58.079Z [19337] - [33mwarn[39m: [plugins] Unable to parse library for: nodebb-plugin-telegram-notifications

**Comment by ToeiRei** [comment]
solution would be `npm install string` - not nice, but okay.
